name: widget-server-pipe

on: 
  push:
    branches:
      - main

jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        id: configure-aws-credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Login to AWS ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push Docker image to AWS ECR
        id: build-and-push-image
        run: | 
          docker build -t api-upload:v3
          docker tag api-upload:v3 938595516706.dkr.ecr.us-east-2.amazonaws.com/kaled/api-upload:v3
          docker push 938595516706.dkr.ecr.us-east-2.amazonaws.com/kaled/api-upload:v3